name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - 'TI_VRX_Docker/Dockerfile' # Specify the path to your Dockerfile here
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd TI_VRX_Docker && docker build . --file Dockerfile --tag robotx:$(date +%s)
